channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - click
  - Sphinx
  - coverage
  - awscli
  - flake8
  - python-dotenv>=0.5.1
  - pandas
  - numpy
  - matplotlib
  - scikit-learn
  - jupyter